from setuptools import setup, find_packages

setup(
    name='federated-learning-framework',
    version='1.0.1',
    description='A professional, modular and extensible framework for federated learning applications with privacy, security, and error recovery.',
    long_description=open('README.md', encoding='utf-8').read(),
    long_description_content_type='text/markdown',
    author='Mehrdad Javadi',
    author_email='mehrdaddjavadi@gmail.com',
    url='https://github.com/mehrdaddjavadi/federated_learning_framework',
    packages=find_packages(),
    classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Developers',
        'Intended Audience :: Education',
        'Intended Audience :: Science/Research',
        'Intended Audience :: Telecommunications Industry',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Topic :: Scientific/Engineering :: Artificial Intelligence',
        'Topic :: Security :: Cryptography',
    ],
    keywords='federated learning, machine learning, deep learning, active learning, encryption, homomorphic encryption, privacy, differential privacy',
    install_requires=[
        'numpy>=1.20.0',
        'websockets>=10.0',
        'cryptography>=3.4.0',
        'scikit-learn>=0.24.0',
    ],
    extras_require={
        'tensorflow': ['tensorflow>=2.6.0'],
        'pytorch': ['torch>=1.9.0'],
        'encryption': ['tenseal>=0.3.0'],
        'visualization': ['matplotlib>=3.3.0', 'pandas>=1.2.0'],
        'dev': [
            'pytest>=6.0.0',
            'pytest-asyncio>=0.18.0',
            'pytest-mock>=3.6.0',
            'black>=22.0.0',
            'pylint>=2.0.0',
            'mypy>=0.950',
        ],
    },
    python_requires='>=3.8',
    include_package_data=True,
    zip_safe=False,
    project_urls={
        'Documentation': 'https://github.com/mehrdaddjavadi/federated_learning_framework',
        'Source Code': 'https://github.com/mehrdaddjavadi/federated_learning_framework',
        'Bug Tracker': 'https://github.com/mehrdaddjavadi/federated_learning_framework/issues',
    },
)
